# Generated by Django 4.2.23 on 2025-07-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_create_date_alter_post_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uploaded_image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
